# -*- coding: utf-8 -*-
"""Words_War.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/AbdulrahmanB-25/Words_War_/blob/main/Words_War.ipynb
"""

# import lib
#!pip install deep-translator

import random
import nltk
from nltk.corpus import words
from deep_translator import GoogleTranslator
import string


nltk.download('words')
web2lowerset = set(w.lower() for w in words.words())

# الاحرف من 1-26
alphabet = {letter: index+1 for index, letter in enumerate(string.ascii_lowercase)}


# الترجمة
def translate_to_arabic(word):
    try:
        return GoogleTranslator(source='en', target='ar').translate(word)
    except:
        return "Translation failed"



# Game Class
class Game():

    def __init__(self):
        self.total_score_p1 = 0
        self.total_score_p2 = 0

    def play_round(self, word1, word2):
#--------توحيد الكلمات

        word1 = word1.lower()
        word2 = word2.lower()

#--------القواعد--------

#--------لا يسمح بلأرقام أو بالرموز
        if not word1.isalpha() or not word2.isalpha():
            print("No numbers or symbols are allowed")
            return
#--------لازم يكونو نفس عدد الاحرف
        if len(word1) != len(word2):
            print("Words must be same length\n")
            return
#--------لازم تكون الكلمة موجودة في هذي المكتبة
        if word1 not in web2lowerset or word2 not in web2lowerset:
            print(f"{word1} not in dictionary\n")
            return
#---------------------- لازم تكون كلمة مو حرف
        if len(word1) ==1 or len(word2) == 1:
          print("Enter a word not a letter\n")
          return

#--------تصفير للنقاط
        round_score1 = 0
        round_score2 = 0

        print("\n" + "="*30)
        print(f"  {word1.lower()}  VS  {word2.lower()}")
        print("="*30)

        for l1, l2 in zip(word1, word2):
            value1 = alphabet[l1]
            value2 = alphabet[l2]

#--------مقارنة بين الحروف

            if value1 > value2:
                round_score1 += value1
                print(f"{l1.lower()} ({value1}) > {l2.lower()} ({value2})  ➜  Player 1 +{value1}")

            elif value2 > value1:
                round_score2 += value2
                print(f"{l2.lower()} ({value2}) > {l1.lower()} ({value1})  ➜  Player 2 +{value2}")

            else:
                print(f"{l1.lower()} ({value1}) = {l2.lower()} ({value2})  ➜  No points")

        # اضفت تحديث السكور
        self.total_score_p1 += round_score1
        self.total_score_p2 += round_score2

        print("-"*30)
        print(f"Round Score → P1: {round_score1} | P2: {round_score2}")

        if round_score1 > round_score2:
            print("Round Winner: Player 1")
        elif round_score2 > round_score1:
            print("Round Winner: Player 2")
        else:
            print("Round Draw")

        print("TOTAL SCORE")
        print(f"Player 1: {self.total_score_p1}")
        print(f"Player 2: {self.total_score_p2}")
        print("="*39)

        print("Arabic Translation:")
        print(f"{word1} → {translate_to_arabic(word1)}")
        print(f"{word2} → {translate_to_arabic(word2)}")
        print("="*30 + "\n")



#--------- اختيار لعب مع الكمبيوتر

    def AI_OR_PVP(self, word1):

      word1 = word1.lower()

      same_length_words = list(
    filter(lambda w: len(w) == len(word1), web2lowerset)
    )
      if not same_length_words:
        print("No matching word length found for computer")
        return
      ai_word = random.choice(same_length_words)
      print(f"\nComputer chose: {ai_word}")

      self.play_round(word1, ai_word)



# Main Loop
game = Game()

while True:

    print("Enter 0 to exit")
    choose = input("Choose mode: 1) PVP 2) VS AI : ").strip()

    if choose == "0":
        print("Game Ended")
        break

    elif choose == "1":
        word1 = input("Enter Word 1: ").strip()
        if word1 == "0":
            print("Game Ended")
            break

        word2 = input("Enter Word 2: ").strip()
        if word2 == "0":
            print("Game Ended")
            break

        game.play_round(word1, word2)

    elif choose == "2":
        word1 = input("Enter word 1: ").strip()
        if word1 == "0":
            print("Game Ended")
            break\

        game.AI_OR_PVP(word1)

    else:
        print("Invalid choice\n")

# Need optmizing
    # Need function for matching word : DONE
    # Need function for Random word : DONE
    # install new dict for explaining  mean of the word : DONE
    # install new dict for translation purpose :  DONE
    # giving the choice to ask the user if he want to play vs bot or pvp : DONE
    # Add an loop if the player chose Player vs Player so it ask for a new word or words DONE
    # If a single letter is inputed the Translation should say letter not word .(Maybe rejcet a single letter ?) DONE
    # Maybe sperate the player from the AI score

